# use the setting below to set multiple docs directories.
# docSections = ["docs", "tutorials"]

disableHome = true

#blogDir = "blog" # can be posts, blog e.t.c

repo = "https://github.com/dezswap/docs/"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 7

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = false

# By default the template will look for icons under the icons directory. In some situations you might wanna change that. edit the line below
# iconsPath = 'icons/'

# Site logo
[logo]
  lightMode = "images/dezswap-primary-logo.svg"

[[source]]
  name = "Twitter"
  iconLight = "images/twitter-logo-black.png"
  url = "https://twitter.com/dezswap_io"

[[source]]
  name = "Discord"
  iconLight = "images/discord-mark-black.png"
  url = "https://discord.gg/ZQ2ps5H64t"

[[source]]
  name = "Github"
  iconLight = "images/github-mark-black.svg"
  url = "https://github.com/dezswap"

# optional
# attribution. Feel free to delete this
[author]
  name = "DELIGHT"
  url = "https://delightlabs.io/"
